# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inputMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inputMessage.proto',
  package='org.auvua.model.dangerZona.hardware.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x12inputMessage.proto\x12)org.auvua.model.dangerZona.hardware.proto\"\x9f\x01\n\x0cInputMessage\x12\r\n\x05motor\x18\x01 \x03(\x01\x12\x10\n\x08\x61\x63tuator\x18\x02 \x03(\x08\x12\x0e\n\x06switch\x18\x03 \x03(\x08\x12\x12\n\nfrontGoPro\x18\x04 \x02(\x08\x12\x11\n\tdownGoPro\x18\x05 \x02(\x08\x12\x10\n\x08lightRed\x18\x06 \x02(\x01\x12\x12\n\nlightGreen\x18\x07 \x02(\x01\x12\x11\n\tlightBlue\x18\x08 \x02(\x01\x42>\n)org.auvua.model.dangerZona.hardware.protoB\x11InputMessageProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INPUTMESSAGE = _descriptor.Descriptor(
  name='InputMessage',
  full_name='org.auvua.model.dangerZona.hardware.proto.InputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motor', full_name='org.auvua.model.dangerZona.hardware.proto.InputMessage.motor', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actuator', full_name='org.auvua.model.dangerZona.hardware.proto.InputMessage.actuator', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='switch', full_name='org.auvua.model.dangerZona.hardware.proto.InputMessage.switch', index=2,
      number=3, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frontGoPro', full_name='org.auvua.model.dangerZona.hardware.proto.InputMessage.frontGoPro', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='downGoPro', full_name='org.auvua.model.dangerZona.hardware.proto.InputMessage.downGoPro', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lightRed', full_name='org.auvua.model.dangerZona.hardware.proto.InputMessage.lightRed', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lightGreen', full_name='org.auvua.model.dangerZona.hardware.proto.InputMessage.lightGreen', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lightBlue', full_name='org.auvua.model.dangerZona.hardware.proto.InputMessage.lightBlue', index=7,
      number=8, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=225,
)

DESCRIPTOR.message_types_by_name['InputMessage'] = _INPUTMESSAGE

InputMessage = _reflection.GeneratedProtocolMessageType('InputMessage', (_message.Message,), dict(
  DESCRIPTOR = _INPUTMESSAGE,
  __module__ = 'inputMessage_pb2'
  # @@protoc_insertion_point(class_scope:org.auvua.model.dangerZona.hardware.proto.InputMessage)
  ))
_sym_db.RegisterMessage(InputMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n)org.auvua.model.dangerZona.hardware.protoB\021InputMessageProto'))
# @@protoc_insertion_point(module_scope)
