# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: outputMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='outputMessage.proto',
  package='org.auvua.model.dangerZona.hardware.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x13outputMessage.proto\x12)org.auvua.model.dangerZona.hardware.proto\"\x8d\x01\n\rOutputMessage\x12\r\n\x05gyroX\x18\x01 \x02(\x01\x12\r\n\x05gyroY\x18\x02 \x02(\x01\x12\r\n\x05gyroZ\x18\x03 \x02(\x01\x12\x0e\n\x06\x61\x63\x63\x65lX\x18\x04 \x02(\x01\x12\x0e\n\x06\x61\x63\x63\x65lY\x18\x05 \x02(\x01\x12\x0e\n\x06\x61\x63\x63\x65lZ\x18\x06 \x02(\x01\x12\r\n\x05\x64\x65pth\x18\x07 \x02(\x01\x12\x10\n\x08humidity\x18\x08 \x02(\x01\x42?\n)org.auvua.model.dangerZona.hardware.protoB\x12OutputMessageProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_OUTPUTMESSAGE = _descriptor.Descriptor(
  name='OutputMessage',
  full_name='org.auvua.model.dangerZona.hardware.proto.OutputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gyroX', full_name='org.auvua.model.dangerZona.hardware.proto.OutputMessage.gyroX', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gyroY', full_name='org.auvua.model.dangerZona.hardware.proto.OutputMessage.gyroY', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gyroZ', full_name='org.auvua.model.dangerZona.hardware.proto.OutputMessage.gyroZ', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accelX', full_name='org.auvua.model.dangerZona.hardware.proto.OutputMessage.accelX', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accelY', full_name='org.auvua.model.dangerZona.hardware.proto.OutputMessage.accelY', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accelZ', full_name='org.auvua.model.dangerZona.hardware.proto.OutputMessage.accelZ', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='depth', full_name='org.auvua.model.dangerZona.hardware.proto.OutputMessage.depth', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='org.auvua.model.dangerZona.hardware.proto.OutputMessage.humidity', index=7,
      number=8, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=208,
)

DESCRIPTOR.message_types_by_name['OutputMessage'] = _OUTPUTMESSAGE

OutputMessage = _reflection.GeneratedProtocolMessageType('OutputMessage', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUTMESSAGE,
  __module__ = 'outputMessage_pb2'
  # @@protoc_insertion_point(class_scope:org.auvua.model.dangerZona.hardware.proto.OutputMessage)
  ))
_sym_db.RegisterMessage(OutputMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n)org.auvua.model.dangerZona.hardware.protoB\022OutputMessageProto'))
# @@protoc_insertion_point(module_scope)
