// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outputMessage.proto

package org.auvua.model.dangerZona.hardware.proto;

public final class OutputMessageProto {
  private OutputMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OutputMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.auvua.model.dangerZona.hardware.proto.OutputMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double gyroX = 1;</code>
     */
    boolean hasGyroX();
    /**
     * <code>required double gyroX = 1;</code>
     */
    double getGyroX();

    /**
     * <code>required double gyroY = 2;</code>
     */
    boolean hasGyroY();
    /**
     * <code>required double gyroY = 2;</code>
     */
    double getGyroY();

    /**
     * <code>required double gyroZ = 3;</code>
     */
    boolean hasGyroZ();
    /**
     * <code>required double gyroZ = 3;</code>
     */
    double getGyroZ();

    /**
     * <code>required double accelX = 4;</code>
     */
    boolean hasAccelX();
    /**
     * <code>required double accelX = 4;</code>
     */
    double getAccelX();

    /**
     * <code>required double accelY = 5;</code>
     */
    boolean hasAccelY();
    /**
     * <code>required double accelY = 5;</code>
     */
    double getAccelY();

    /**
     * <code>required double accelZ = 6;</code>
     */
    boolean hasAccelZ();
    /**
     * <code>required double accelZ = 6;</code>
     */
    double getAccelZ();

    /**
     * <code>required double depth = 7;</code>
     */
    boolean hasDepth();
    /**
     * <code>required double depth = 7;</code>
     */
    double getDepth();

    /**
     * <code>required double humidity = 8;</code>
     */
    boolean hasHumidity();
    /**
     * <code>required double humidity = 8;</code>
     */
    double getHumidity();
  }
  /**
   * Protobuf type {@code org.auvua.model.dangerZona.hardware.proto.OutputMessage}
   */
  public  static final class OutputMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.auvua.model.dangerZona.hardware.proto.OutputMessage)
      OutputMessageOrBuilder {
    // Use OutputMessage.newBuilder() to construct.
    private OutputMessage(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private OutputMessage() {
      gyroX_ = 0D;
      gyroY_ = 0D;
      gyroZ_ = 0D;
      accelX_ = 0D;
      accelY_ = 0D;
      accelZ_ = 0D;
      depth_ = 0D;
      humidity_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OutputMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              gyroX_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              gyroY_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              gyroZ_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              accelX_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              accelY_ = input.readDouble();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              accelZ_ = input.readDouble();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              depth_ = input.readDouble();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              humidity_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.internal_static_org_auvua_model_dangerZona_hardware_proto_OutputMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.internal_static_org_auvua_model_dangerZona_hardware_proto_OutputMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage.class, org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage.Builder.class);
    }

    private int bitField0_;
    public static final int GYROX_FIELD_NUMBER = 1;
    private double gyroX_;
    /**
     * <code>required double gyroX = 1;</code>
     */
    public boolean hasGyroX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double gyroX = 1;</code>
     */
    public double getGyroX() {
      return gyroX_;
    }

    public static final int GYROY_FIELD_NUMBER = 2;
    private double gyroY_;
    /**
     * <code>required double gyroY = 2;</code>
     */
    public boolean hasGyroY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double gyroY = 2;</code>
     */
    public double getGyroY() {
      return gyroY_;
    }

    public static final int GYROZ_FIELD_NUMBER = 3;
    private double gyroZ_;
    /**
     * <code>required double gyroZ = 3;</code>
     */
    public boolean hasGyroZ() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double gyroZ = 3;</code>
     */
    public double getGyroZ() {
      return gyroZ_;
    }

    public static final int ACCELX_FIELD_NUMBER = 4;
    private double accelX_;
    /**
     * <code>required double accelX = 4;</code>
     */
    public boolean hasAccelX() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double accelX = 4;</code>
     */
    public double getAccelX() {
      return accelX_;
    }

    public static final int ACCELY_FIELD_NUMBER = 5;
    private double accelY_;
    /**
     * <code>required double accelY = 5;</code>
     */
    public boolean hasAccelY() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required double accelY = 5;</code>
     */
    public double getAccelY() {
      return accelY_;
    }

    public static final int ACCELZ_FIELD_NUMBER = 6;
    private double accelZ_;
    /**
     * <code>required double accelZ = 6;</code>
     */
    public boolean hasAccelZ() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required double accelZ = 6;</code>
     */
    public double getAccelZ() {
      return accelZ_;
    }

    public static final int DEPTH_FIELD_NUMBER = 7;
    private double depth_;
    /**
     * <code>required double depth = 7;</code>
     */
    public boolean hasDepth() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required double depth = 7;</code>
     */
    public double getDepth() {
      return depth_;
    }

    public static final int HUMIDITY_FIELD_NUMBER = 8;
    private double humidity_;
    /**
     * <code>required double humidity = 8;</code>
     */
    public boolean hasHumidity() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required double humidity = 8;</code>
     */
    public double getHumidity() {
      return humidity_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasGyroX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGyroY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGyroZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccelX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccelY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccelZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDepth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHumidity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, gyroX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, gyroY_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, gyroZ_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, accelX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, accelY_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, accelZ_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, depth_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeDouble(8, humidity_);
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, gyroX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, gyroY_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, gyroZ_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, accelX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, accelY_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, accelZ_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, depth_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, humidity_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.auvua.model.dangerZona.hardware.proto.OutputMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.auvua.model.dangerZona.hardware.proto.OutputMessage)
        org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.internal_static_org_auvua_model_dangerZona_hardware_proto_OutputMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.internal_static_org_auvua_model_dangerZona_hardware_proto_OutputMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage.class, org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage.Builder.class);
      }

      // Construct using org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        gyroX_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        gyroY_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        gyroZ_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        accelX_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        accelY_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        accelZ_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        depth_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        humidity_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.internal_static_org_auvua_model_dangerZona_hardware_proto_OutputMessage_descriptor;
      }

      public org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage getDefaultInstanceForType() {
        return org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage.getDefaultInstance();
      }

      public org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage build() {
        org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage buildPartial() {
        org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage result = new org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gyroX_ = gyroX_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gyroY_ = gyroY_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gyroZ_ = gyroZ_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.accelX_ = accelX_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.accelY_ = accelY_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.accelZ_ = accelZ_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.depth_ = depth_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.humidity_ = humidity_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage) {
          return mergeFrom((org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage other) {
        if (other == org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage.getDefaultInstance()) return this;
        if (other.hasGyroX()) {
          setGyroX(other.getGyroX());
        }
        if (other.hasGyroY()) {
          setGyroY(other.getGyroY());
        }
        if (other.hasGyroZ()) {
          setGyroZ(other.getGyroZ());
        }
        if (other.hasAccelX()) {
          setAccelX(other.getAccelX());
        }
        if (other.hasAccelY()) {
          setAccelY(other.getAccelY());
        }
        if (other.hasAccelZ()) {
          setAccelZ(other.getAccelZ());
        }
        if (other.hasDepth()) {
          setDepth(other.getDepth());
        }
        if (other.hasHumidity()) {
          setHumidity(other.getHumidity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGyroX()) {
          return false;
        }
        if (!hasGyroY()) {
          return false;
        }
        if (!hasGyroZ()) {
          return false;
        }
        if (!hasAccelX()) {
          return false;
        }
        if (!hasAccelY()) {
          return false;
        }
        if (!hasAccelZ()) {
          return false;
        }
        if (!hasDepth()) {
          return false;
        }
        if (!hasHumidity()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double gyroX_ ;
      /**
       * <code>required double gyroX = 1;</code>
       */
      public boolean hasGyroX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double gyroX = 1;</code>
       */
      public double getGyroX() {
        return gyroX_;
      }
      /**
       * <code>required double gyroX = 1;</code>
       */
      public Builder setGyroX(double value) {
        bitField0_ |= 0x00000001;
        gyroX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double gyroX = 1;</code>
       */
      public Builder clearGyroX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gyroX_ = 0D;
        onChanged();
        return this;
      }

      private double gyroY_ ;
      /**
       * <code>required double gyroY = 2;</code>
       */
      public boolean hasGyroY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double gyroY = 2;</code>
       */
      public double getGyroY() {
        return gyroY_;
      }
      /**
       * <code>required double gyroY = 2;</code>
       */
      public Builder setGyroY(double value) {
        bitField0_ |= 0x00000002;
        gyroY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double gyroY = 2;</code>
       */
      public Builder clearGyroY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gyroY_ = 0D;
        onChanged();
        return this;
      }

      private double gyroZ_ ;
      /**
       * <code>required double gyroZ = 3;</code>
       */
      public boolean hasGyroZ() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double gyroZ = 3;</code>
       */
      public double getGyroZ() {
        return gyroZ_;
      }
      /**
       * <code>required double gyroZ = 3;</code>
       */
      public Builder setGyroZ(double value) {
        bitField0_ |= 0x00000004;
        gyroZ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double gyroZ = 3;</code>
       */
      public Builder clearGyroZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gyroZ_ = 0D;
        onChanged();
        return this;
      }

      private double accelX_ ;
      /**
       * <code>required double accelX = 4;</code>
       */
      public boolean hasAccelX() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double accelX = 4;</code>
       */
      public double getAccelX() {
        return accelX_;
      }
      /**
       * <code>required double accelX = 4;</code>
       */
      public Builder setAccelX(double value) {
        bitField0_ |= 0x00000008;
        accelX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double accelX = 4;</code>
       */
      public Builder clearAccelX() {
        bitField0_ = (bitField0_ & ~0x00000008);
        accelX_ = 0D;
        onChanged();
        return this;
      }

      private double accelY_ ;
      /**
       * <code>required double accelY = 5;</code>
       */
      public boolean hasAccelY() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required double accelY = 5;</code>
       */
      public double getAccelY() {
        return accelY_;
      }
      /**
       * <code>required double accelY = 5;</code>
       */
      public Builder setAccelY(double value) {
        bitField0_ |= 0x00000010;
        accelY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double accelY = 5;</code>
       */
      public Builder clearAccelY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        accelY_ = 0D;
        onChanged();
        return this;
      }

      private double accelZ_ ;
      /**
       * <code>required double accelZ = 6;</code>
       */
      public boolean hasAccelZ() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required double accelZ = 6;</code>
       */
      public double getAccelZ() {
        return accelZ_;
      }
      /**
       * <code>required double accelZ = 6;</code>
       */
      public Builder setAccelZ(double value) {
        bitField0_ |= 0x00000020;
        accelZ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double accelZ = 6;</code>
       */
      public Builder clearAccelZ() {
        bitField0_ = (bitField0_ & ~0x00000020);
        accelZ_ = 0D;
        onChanged();
        return this;
      }

      private double depth_ ;
      /**
       * <code>required double depth = 7;</code>
       */
      public boolean hasDepth() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required double depth = 7;</code>
       */
      public double getDepth() {
        return depth_;
      }
      /**
       * <code>required double depth = 7;</code>
       */
      public Builder setDepth(double value) {
        bitField0_ |= 0x00000040;
        depth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double depth = 7;</code>
       */
      public Builder clearDepth() {
        bitField0_ = (bitField0_ & ~0x00000040);
        depth_ = 0D;
        onChanged();
        return this;
      }

      private double humidity_ ;
      /**
       * <code>required double humidity = 8;</code>
       */
      public boolean hasHumidity() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required double humidity = 8;</code>
       */
      public double getHumidity() {
        return humidity_;
      }
      /**
       * <code>required double humidity = 8;</code>
       */
      public Builder setHumidity(double value) {
        bitField0_ |= 0x00000080;
        humidity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double humidity = 8;</code>
       */
      public Builder clearHumidity() {
        bitField0_ = (bitField0_ & ~0x00000080);
        humidity_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.auvua.model.dangerZona.hardware.proto.OutputMessage)
    }

    // @@protoc_insertion_point(class_scope:org.auvua.model.dangerZona.hardware.proto.OutputMessage)
    private static final org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage();
    }

    public static org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<OutputMessage> PARSER =
        new com.google.protobuf.AbstractParser<OutputMessage>() {
      public OutputMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new OutputMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OutputMessage> getParserForType() {
      return PARSER;
    }

    public org.auvua.model.dangerZona.hardware.proto.OutputMessageProto.OutputMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_auvua_model_dangerZona_hardware_proto_OutputMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_auvua_model_dangerZona_hardware_proto_OutputMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023outputMessage.proto\022)org.auvua.model.d" +
      "angerZona.hardware.proto\"\215\001\n\rOutputMessa" +
      "ge\022\r\n\005gyroX\030\001 \002(\001\022\r\n\005gyroY\030\002 \002(\001\022\r\n\005gyro" +
      "Z\030\003 \002(\001\022\016\n\006accelX\030\004 \002(\001\022\016\n\006accelY\030\005 \002(\001\022" +
      "\016\n\006accelZ\030\006 \002(\001\022\r\n\005depth\030\007 \002(\001\022\020\n\010humidi" +
      "ty\030\010 \002(\001B?\n)org.auvua.model.dangerZona.h" +
      "ardware.protoB\022OutputMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_auvua_model_dangerZona_hardware_proto_OutputMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_auvua_model_dangerZona_hardware_proto_OutputMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_auvua_model_dangerZona_hardware_proto_OutputMessage_descriptor,
        new java.lang.String[] { "GyroX", "GyroY", "GyroZ", "AccelX", "AccelY", "AccelZ", "Depth", "Humidity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
